name: build.yml
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      TARGET: armv7-unknown-linux-musleabihf
      # TARGET: arm-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 7027d45303b412be6fa9c09d689cc6276748fb38
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.13.0
      - run: cargo install cargo-zigbuild --locked
      - run: cargo zigbuild --target ${{ env.TARGET }} --release
      - run: |
          mkdir -p build
          cp target/${{ env.TARGET }}/release/fd build/fd
      - uses: actions/upload-artifact@v7
        with:
          name: fd-binary
          path: build/